### ISSUE TITLE
是否可以支持child template disable掉parent template的某个strategy ？

### ISSUE THREAD

**Issue by hackstoic** [open-falcon/portal#16]
场景需求如下：

Linux 主机a 使用了linux os 标准模版，但是其中对于linux os某个策略（如cpu.used > 50% 告警）不想继承并应用， 可不可以通过某种方式把这条策略给disable掉？

我们想到的方式是用新建一个子模板，给metric设置一个不可能达到的告警阀值（设置cpu.used > 120%  告警）来实现上述的需求。 但是这种方式比较不太优雅。 

有没有原生支持的方式？或者需要进行二次开发？

**Comment by itxx00** [comment]
使用模板继承的方式，子模板里面设置自定义阈值，你说的这种方式就是原生支持的

**Comment by laiwei** [comment]
@hackstoic 嗯，只能是子模板继承覆盖父模板，子模板设置一个不会触发的阈值，来覆盖掉父模板对应的项。

**Comment by hackstoic** [comment]
@laiwei 谢谢。如果strategy增加一个state字段，当state为false的时候， 就可以把strategy disable掉。使用这种方式会不会更好， 个人觉得这样的话比起想办法去设置一个不会触发的阈值更简洁明了，没有歧义。

**Comment by hackstoic** [comment]
@laiwei  既然子模板可以改父模板的值， 是否也应该直接提供删除父模板的值的机制？ 您觉得在strategy增加一个state字段的方式是否有不合理的地方？
