### ISSUE TITLE
是否支持客户端自动注册和批量添加主机到Hostgroup

### ISSUE THREAD

**Issue by ipcpu** [open-falcon/portal#18]
比如我这里每周会新增50左右服务器，名字都是DS-xxxx

怎样才能让agent启动后，主机能自动进入到相应的Hostgroup里？

要是每次都手动去添加太麻烦了，zabbix的自动注册功能就不错，不需要手工干预。

至于批量添加主机到Hostgroup，希望可以新增主机时填写“DS-*” 这样把所有DS- 开头的主机都加进去

相关代码 portal/web/model/group_host.py

**Comment by itxx00** [comment]
你这里描述的问题本质其实是如何将已有cmdb信息同步到portal当中。支持自动注册是解决这个问题的途径之一，把问题扩展一下，就可以看到不止这一种方法可以解决这个问题。通常的cmdb管理是分层级树状结构的，但是这里开源版本的portal实现比较简单是扁平结构的，你可以二次开发和自有cmdb相结合，或者简单点写一个脚本从cmdb同步数据过来。

**Comment by ipcpu** [comment]
有道理，好吧，我写脚本实现吧。

**Comment by laiwei** [comment]
@itxx00 该说的都说了，赞
