### ISSUE TITLE
自定义的Endpoint，无法添加到某个主机组

### ISSUE THREAD

**Issue by wkshare** [open-falcon/portal#3]
主机组，可以添加的Endpoint必须由heatbeat添加。
如果没有heatbeat添加，那么就无法添加到主机组，是这样吗？
@UlricQin

**Comment by itxx00** [comment]
可以自己操作数据库进行添加的

## 

_Regards,_
_GaoYongwei_

2015-07-31 0:58 GMT+08:00 wkshare notifications@github.com:

**Comment by UlricQin** [comment]
@itxx00 说得对，可以手工操作host表，插入。

下个阶段准备改造一下这块逻辑，在往HostGroup中添加机器的时候如果发现机器名不存在，就直接插入host表， @wkshare 看看可以提交个patch

**Comment by modeyang** [comment]
+1  这个添加host逻辑， 请问有计划表吗？

**Comment by laiwei** [comment]
@wkshare 可否提交一个pull-request来解决这个问题，thx

**Comment by wkshare** [comment]
@laiwei  我尝试一下。

**Comment by laiwei** [comment]
@wkshare 谢谢

**Comment by wkshare** [comment]
@laiwei @UlricQin 提了个PR。

最近一直在想类似于CMDB的东西该怎么整，如何接入到一套新的监控系统，有什么好的方案吗？就像机器管理、服务树。

**Comment by ZeaLoVe** [comment]
刚看了0.1.0 realease的文章，觉得这个特性有点坑啊。这样没办法做校验了，如果用户手误输错了几个字母，也添加成功了，会导致很高的报警漏报风险（认真查看可以减少风险，是一个方案）。我的做法是在hbs中增加添加虚拟主机的接口（直接写数据库），将虚拟主机定义为ip为0.0.0.0（这个定义可以随便），这样至少可以保证手误导致的漏报风险，自己去把控需要监控的非真实的endpoint

**Comment by laiwei** [comment]
@ZeaLoVe 你这个考虑是对的

这个fix是一个短期的方案，长期来看，dashboard中所有的endpoint，和portal中的host，应该是打通的。

下个版本会考虑

**Comment by ZeaLoVe** [comment]
@laiwei  恩，真心希望open-falcon能越来越好。
